{
 "title": "SDE Server Group - OverAll",
 "description": "InfluxDB dashboards for telegraf metrics",
 "time": { "from": "2021-03-22T09:42:47.853Z", "to": "2021-03-22T12:57:18.938Z" },
 "templating": {
  "list": [
   {
    "name": "domainId",
    "label": "업무구분",
    "query": "hsc,eng,mat,jhs,pri,man,lan,api,cmp"
   },
   {
    "name": "bizType",
    "label": "업무구분",
    "query": "SHOW TAG VALUES FROM system WITH KEY= host where host =~ /-was-/ and host =~ /$domainId/"
   },
   {
    "name": "web",
    "label": "Web Server",
    "query": "SHOW TAG VALUES FROM system WITH KEY= host where host =~ /-web-/ and host =~ /$domainId-$bizType/"
   },
   {
    "name": "was",
    "label": "WAS Server",
    "query": "SHOW TAG VALUES FROM system WITH KEY= host where host =~ /-was-/ and host =~ /$domainId-$bizType/"
   },
   {
    "name": "redis",
    "label": "Redis Server",
    "query": "SHOW TAG VALUES FROM system WITH KEY= host where host =~ /-redis-/ and host =~ /$domainId/"
   },
   {
    "name": "webNodeId",
    "query": "SHOW TAG VALUES FROM system WITH KEY= host where host =~ /-web-/ and host =~ /$bizType/"
   },
   {
    "name": "wasNodeId",
    "query": "SHOW TAG VALUES FROM system WITH KEY= host where host =~ /-was-/ and host =~ /$bizType/"
   },
   { "name": "inter", "label": "Interval", "query": "5s,10s,30s,1m,2m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "$domainId - Overall Current Status ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Web Server $domainId - $bizType",
   "type": "mxswat-separator-panel",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 1 }
  },
  {
   "title": "WAS Server $domainId - $bizType",
   "type": "mxswat-separator-panel",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 1 }
  },
  { "title": "Redis Server $domainId", "type": "mxswat-separator-panel", "gridPos": { "h": 1, "w": 6, "x": 12, "y": 1 } },
  { "title": "DBMS Server $domainId", "type": "mxswat-separator-panel", "gridPos": { "h": 1, "w": 6, "x": 18, "y": 1 } },
  {
   "title": "CPU - $webNodeId",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2 },
   "repeat": "webNodeId",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT 100 - mean(\"usage_idle\") FROM \"cpu\" WHERE (\"host\" =~ /$web/) AND (\"host\" =~ /$webNodeId/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "user" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "system" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_steal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "steal" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$web$/" }
     ]
    }
   ]
  },
  {
   "title": "ContextSwitch - $webNodeId",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 2 },
   "repeat": "webNodeId",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$webNodeId",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "kernel",
     "query": "SELECT mean(usage_user) + mean(usage_system) as \"Usage\"  FROM \"cpu\" WHERE \"host\" =~ /$server$/ and  cpu = 'cpu-total' AND $timeFilter GROUP BY time($__interval), *",
     "select": [
      [
       { "params": [ "context_switches" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "ContextSwitch" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$web$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/$webNodeId$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU - $wasNodeId",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 2 },
   "repeat": "wasNodeId",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT 100 - mean(\"usage_idle\") FROM \"cpu\" WHERE (\"host\" =~ /$was/) AND (\"host\" =~ /$wasNodeId/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "user" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "system" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_steal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "steal" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$web$/" }
     ]
    }
   ]
  },
  {
   "title": "ContextSwitch - $wasNodeId",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 2 },
   "repeat": "wasNodeId",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$webNodeId",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "kernel",
     "query": "SELECT mean(usage_user) + mean(usage_system) as \"Usage\"  FROM \"cpu\" WHERE \"host\" =~ /$server$/ and  cpu = 'cpu-total' AND $timeFilter GROUP BY time($__interval), *",
     "select": [
      [
       { "params": [ "context_switches" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "ContextSwitch" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$was$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/$wasNodeId$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU - Data Cache",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT 100 - mean(\"usage_idle\") FROM \"cpu\" WHERE \"host\" =~ /-redis-dat/ and host =~ /$domainId/  AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "user" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "system" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_steal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "steal" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$web$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT 100 - mean(\"usage_idle\") FROM \"cpu\" WHERE \"host\" =~ /-db-/ and host =~ /$domainId/  AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "user" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "system" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_steal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "steal" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$web$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU - $webNodeId",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT 100 - mean(\"usage_idle\") FROM \"cpu\" WHERE (\"host\" =~ /$web/) AND (\"host\" =~ /$webNodeId/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "user" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "system" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_steal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "steal" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$web$/" }
     ]
    }
   ]
  },
  {
   "title": "ContextSwitch - $webNodeId",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$webNodeId",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "kernel",
     "query": "SELECT mean(usage_user) + mean(usage_system) as \"Usage\"  FROM \"cpu\" WHERE \"host\" =~ /$server$/ and  cpu = 'cpu-total' AND $timeFilter GROUP BY time($__interval), *",
     "select": [
      [
       { "params": [ "context_switches" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "ContextSwitch" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$web$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/$webNodeId$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU - $wasNodeId",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT 100 - mean(\"usage_idle\") FROM \"cpu\" WHERE (\"host\" =~ /$was/) AND (\"host\" =~ /$wasNodeId/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "user" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "system" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_steal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "steal" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$web$/" }
     ]
    }
   ]
  },
  {
   "title": "ContextSwitch - $wasNodeId",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$webNodeId",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "kernel",
     "query": "SELECT mean(usage_user) + mean(usage_system) as \"Usage\"  FROM \"cpu\" WHERE \"host\" =~ /$server$/ and  cpu = 'cpu-total' AND $timeFilter GROUP BY time($__interval), *",
     "select": [
      [
       { "params": [ "context_switches" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "ContextSwitch" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$was$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/$wasNodeId$/" }
     ]
    }
   ]
  },
  {
   "title": "ContextSwitch - Data Cache",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_host",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "kernel",
     "query": "SELECT mean(usage_user) + mean(usage_system) as \"Usage\"  FROM \"cpu\" WHERE \"host\" =~ /$server$/ and  cpu = 'cpu-total' AND $timeFilter GROUP BY time($__interval), *",
     "select": [
      [
       { "params": [ "context_switches" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "ContextSwitch" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/-redis-dat/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/$domainId/" }
     ]
    }
   ]
  },
  {
   "title": "ContextSwitch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_host",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "kernel",
     "query": "SELECT mean(usage_user) + mean(usage_system) as \"Usage\"  FROM \"cpu\" WHERE \"host\" =~ /$server$/ and  cpu = 'cpu-total' AND $timeFilter GROUP BY time($__interval), *",
     "select": [
      [
       { "params": [ "context_switches" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "ContextSwitch" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/db/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/$domainId/" }
     ]
    }
   ]
  },
  {
   "title": "Network ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host $col",
     "function": "derivative",
     "groupBy": [
      { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
      { "key": "host", "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT non_negative_derivative(mean(bytes_recv),1s) as \"in\" FROM \"net\" WHERE host =~ /$web/ AND interface =~ /(vlan|eth|bond).*/ AND $timeFilter GROUP BY time($__interval), * fill(none)",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "out" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "in" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$web$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/$domainId/" }
     ]
    }
   ]
  },
  {
   "title": "Network ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host $col",
     "function": "derivative",
     "groupBy": [
      { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
      { "key": "host", "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT non_negative_derivative(mean(bytes_recv),1s) as \"in\" FROM \"net\" WHERE host =~ /$web/ AND interface =~ /(vlan|eth|bond).*/ AND $timeFilter GROUP BY time($__interval), * fill(none)",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "out" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "in" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$was$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/$domainId/" }
     ]
    }
   ]
  },
  {
   "title": "Network - Data Cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host $col",
     "function": "derivative",
     "groupBy": [
      { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
      { "key": "host", "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT non_negative_derivative(mean(bytes_recv),1s) as \"in\" FROM \"net\" WHERE host =~ /$web/ AND interface =~ /(vlan|eth|bond).*/ AND $timeFilter GROUP BY time($__interval), * fill(none)",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "out" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "in" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/-redis-dat/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/$domainId/" }
     ]
    }
   ]
  },
  {
   "title": "Network ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host $col",
     "function": "derivative",
     "groupBy": [
      { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
      { "key": "host", "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT non_negative_derivative(mean(bytes_recv),1s) as \"in\" FROM \"net\" WHERE host =~ /$web/ AND interface =~ /(vlan|eth|bond).*/ AND $timeFilter GROUP BY time($__interval), * fill(none)",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "out" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "in" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/-db-/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/$domainId/" }
     ]
    }
   ]
  },
  {
   "title": "Workers - $webNodeId",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 18 },
   "repeat": "webNodeId",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apache",
     "select": [
      [
       { "params": [ "IdleWorkers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Idle" ], "type": "alias" }
      ],
      [
       { "params": [ "BusyWorkers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Busy" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$web$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/$webNodeId$/" }
     ]
    }
   ]
  },
  {
   "title": "Accesses / Second - $webNodeId",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 18 },
   "repeat": "webNodeId",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apache",
     "select": [
      [
       { "params": [ "TotalAccesses" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$web$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/$webNodeId$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory - $wasNodeId",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 18 },
   "repeat": "wasNodeId",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Total" ], "type": "alias" }
      ],
      [
       { "params": [ "available" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Available" ], "type": "alias" }
      ],
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Used" ], "type": "alias" }
      ],
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Free" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$was$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/$wasNodeId$/" }
     ]
    }
   ]
  },
  {
   "title": "Cmp Session Store",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "command": "info", "section": "stats", "type": "command" }
   ]
  },
  {
   "title": "Hsc Session Store",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "command": "info", "section": "stats", "type": "command" }
   ]
  },
  {
   "title": "Queries",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_host",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "mysql",
     "query": "SELECT mean(usage_user) + mean(usage_system) as \"Usage\"  FROM \"cpu\" WHERE \"host\" =~ /$server$/ and  cpu = 'cpu-total' AND $timeFilter GROUP BY time($__interval), *",
     "select": [
      [
       { "params": [ "queries" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/-db-/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/$domainId/" }
     ]
    }
   ]
  },
  {
   "title": "Cmp Session Network",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "command": "info", "section": "stats", "type": "command" }
   ]
  },
  {
   "title": "Hsc Session Network",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "command": "info", "section": "stats", "type": "command" }
   ]
  },
  {
   "title": "MySQL Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_host $col",
     "function": "derivative",
     "groupBy": [
      { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
      { "key": "host", "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "mysql",
     "query": "SELECT non_negative_derivative(mean(bytes_recv),1s) as \"in\" FROM \"net\" WHERE host =~ /$web/ AND interface =~ /(vlan|eth|bond).*/ AND $timeFilter GROUP BY time($__interval), * fill(none)",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "out" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_received" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "in" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/-db-/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/$domainId/" }
     ]
    }
   ]
  },
  {
   "title": "Workers - $webNodeId",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apache",
     "select": [
      [
       { "params": [ "IdleWorkers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Idle" ], "type": "alias" }
      ],
      [
       { "params": [ "BusyWorkers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Busy" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$web$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/$webNodeId$/" }
     ]
    }
   ]
  },
  {
   "title": "Accesses / Second - $webNodeId",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apache",
     "select": [
      [
       { "params": [ "TotalAccesses" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$web$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/$webNodeId$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory - $wasNodeId",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Total" ], "type": "alias" }
      ],
      [
       { "params": [ "available" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Available" ], "type": "alias" }
      ],
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Used" ], "type": "alias" }
      ],
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Free" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$was$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/$wasNodeId$/" }
     ]
    }
   ]
  },
  {
   "title": "Cmp Session Store Memory",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "command": "info", "section": "memory", "type": "command" }
   ]
  },
  {
   "title": "Hsc Session Store Memory",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "command": "info", "section": "memory", "type": "command" }
   ]
  },
  {
   "title": "Requests / Second - $webNodeId",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 26 },
   "repeat": "webNodeId",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apache",
     "select": [
      [
       { "params": [ "ReqPerSec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$web$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/$webNodeId$/" }
     ]
    }
   ]
  },
  {
   "title": "Processes- $wasNodeId",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 26 },
   "repeat": "wasNodeId",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "query": "SELECT 100 - mean(\"usage_idle\") FROM \"cpu\" WHERE (\"host\" =~ /$was/) AND (\"host\" =~ /$wasNodeId/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "processes" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$was$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/$wasNodeId$/" }
     ]
    }
   ]
  },
  {
   "title": "Threads- $wasNodeId",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 26 },
   "repeat": "wasNodeId",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "query": "SELECT 100 - mean(\"usage_idle\") FROM \"cpu\" WHERE (\"host\" =~ /$was/) AND (\"host\" =~ /$wasNodeId/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "total_threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Threads" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$was$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/$wasNodeId$/" }
     ]
    }
   ]
  },
  {
   "title": "Requests / Second - $webNodeId",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apache",
     "select": [
      [
       { "params": [ "ReqPerSec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$web$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/$webNodeId$/" }
     ]
    }
   ]
  },
  {
   "title": "Cmp Session Store Clients",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "command": "info", "section": "clients", "type": "command" }
   ]
  },
  {
   "title": "Hsc Session Store Clients",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "command": "info", "section": "clients", "type": "command" }
   ]
  },
  {
   "title": "Processes- $wasNodeId",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "query": "SELECT 100 - mean(\"usage_idle\") FROM \"cpu\" WHERE (\"host\" =~ /$was/) AND (\"host\" =~ /$wasNodeId/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "processes" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$was$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/$wasNodeId$/" }
     ]
    }
   ]
  },
  {
   "title": "Threads- $wasNodeId",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "query": "SELECT 100 - mean(\"usage_idle\") FROM \"cpu\" WHERE (\"host\" =~ /$was/) AND (\"host\" =~ /$wasNodeId/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "total_threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Threads" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$was$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/$wasNodeId$/" }
     ]
    }
   ]
  },
  {
   "title": "Slow Queries",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_host",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "mysql",
     "query": "SELECT mean(usage_user) + mean(usage_system) as \"Usage\"  FROM \"cpu\" WHERE \"host\" =~ /$server$/ and  cpu = 'cpu-total' AND $timeFilter GROUP BY time($__interval), *",
     "select": [
      [
       { "params": [ "slow_queries" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/-db-/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/$domainId/" }
     ]
    }
   ]
  },
  {
   "title": "Bytes per Requests - $webNodeId",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 30 },
   "repeat": "webNodeId",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apache",
     "select": [
      [
       { "params": [ "BytesPerSec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$web$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/$webNodeId$/" }
     ]
    }
   ]
  },
  {
   "title": "Bytes per Seconds - $webNodeId",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 30 },
   "repeat": "webNodeId",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apache",
     "select": [
      [
       { "params": [ "BytesPerSec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$web$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/$webNodeId$/" }
     ]
    }
   ]
  },
  {
   "title": "Cmp Session Store Keys",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "query": "dbsize", "section": "clients", "type": "cli" }
   ]
  },
  {
   "title": "Hsc Session Store Keys",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "query": "dbsize", "section": "stats", "type": "cli" }
   ]
  },
  {
   "title": "Forks - $wasNodeId",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 32 },
   "repeat": "wasNodeId",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kernel",
     "select": [
      [
       { "params": [ "processes_forked" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$was$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/$wasNodeId$/" }
     ]
    }
   ]
  },
  {
   "title": "Operations / sec. - Data Cache",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "redis_used_cpu_sys",
     "query": "SELECT mean(\"instantaneous_ops_per_sec\") as \"ops\" FROM \"redis\" WHERE host =~ /$domainId-redis-dat/ AND $timeFilter GROUP BY time($__interval),* fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active Threads",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_host $col",
     "function": "derivative",
     "groupBy": [
      { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
      { "key": "host", "params": [ "host" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "mysql",
     "query": "SELECT non_negative_derivative(mean(bytes_recv),1s) as \"in\" FROM \"net\" WHERE host =~ /$web/ AND interface =~ /(vlan|eth|bond).*/ AND $timeFilter GROUP BY time($__interval), * fill(none)",
     "select": [
      [
       { "params": [ "threads_connected" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Connected" ], "type": "alias" }
      ],
      [
       { "params": [ "threads_running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Running" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/-db-/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/$domainId/" }
     ]
    }
   ]
  },
  {
   "title": "Bytes per Requests - $webNodeId",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apache",
     "select": [
      [
       { "params": [ "BytesPerSec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$web$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/$webNodeId$/" }
     ]
    }
   ]
  },
  {
   "title": "Bytes per Seconds - $webNodeId",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apache",
     "select": [
      [
       { "params": [ "BytesPerSec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$web$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/$webNodeId$/" }
     ]
    }
   ]
  },
  {
   "title": "Forks - $wasNodeId",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kernel",
     "select": [
      [
       { "params": [ "processes_forked" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$was$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/$wasNodeId$/" }
     ]
    }
   ]
  },
  {
   "title": "$domainId - Disk IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Web Server $domainId - $bizType",
     "type": "mxswat-separator-panel",
     "gridPos": { "h": 1, "w": 6, "x": 0, "y": 2 }
    },
    {
     "title": "WAS Server $domainId - $bizType",
     "type": "mxswat-separator-panel",
     "gridPos": { "h": 1, "w": 6, "x": 6, "y": 2 }
    },
    { "title": "Redis Server $domainId", "type": "mxswat-separator-panel", "gridPos": { "h": 1, "w": 6, "x": 12, "y": 2 } },
    { "title": "DBMS Server $domainId", "type": "mxswat-separator-panel", "gridPos": { "h": 1, "w": 6, "x": 18, "y": 2 } },
    {
     "title": "Disk I/O bytes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "decbits" } },
     "yaxes": [
      { "format": "decbits" }
     ],
     "targets": [
      {
       "alias": "$tag_host $tag_name $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "write_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ "write" ], "type": "alias" }
        ],
        [
         { "params": [ "read_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ "read" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$web$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$domainId/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/xvd[a|b]$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk I/O bytes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "decbits" } },
     "yaxes": [
      { "format": "decbits" }
     ],
     "targets": [
      {
       "alias": "$tag_host $tag_name $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "write_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ "write" ], "type": "alias" }
        ],
        [
         { "params": [ "read_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ "read" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$was$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$domainId/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/xvd[a|b]$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk I/O bytes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "decbits" } },
     "yaxes": [
      { "format": "decbits" }
     ],
     "targets": [
      {
       "alias": "$tag_host $tag_name $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "write_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ "write" ], "type": "alias" }
        ],
        [
         { "params": [ "read_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ "read" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/-redis-/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$domainId/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/xvd[a|b]$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk I/O bytes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "decbits" } },
     "yaxes": [
      { "format": "decbits" }
     ],
     "targets": [
      {
       "alias": "$tag_host $tag_name $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "write_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ "write" ], "type": "alias" }
        ],
        [
         { "params": [ "read_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ "read" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/-db-/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$domainId/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/xvd[a|b]$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk I/O requests",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host $tag_name $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "writes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ "write" ], "type": "alias" }
        ],
        [
         { "params": [ "reads" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ "read" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$web$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$domainId/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/xvd[a|b]$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk I/O requests",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host $tag_name $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "writes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ "write" ], "type": "alias" }
        ],
        [
         { "params": [ "reads" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ "read" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$was$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$domainId/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/xvd[a|b]$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk I/O requests",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host $tag_name $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "writes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ "write" ], "type": "alias" }
        ],
        [
         { "params": [ "reads" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ "read" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/-redis-/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$domainId/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/xvd[a|b]$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk I/O requests",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host $tag_name $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "writes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ "write" ], "type": "alias" }
        ],
        [
         { "params": [ "reads" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ "read" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/-db-/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$domainId/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/xvd[a|b]$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}