{
 "title": "SDE Server Group Trend By Telegraf - Overall",
 "description": "SDE Dashboard",
 "time": {
  "from": "now-3h",
  "now": false,
  "to": "now"
 },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ServerType", "query": "was,web,redis,db" },
   {
    "name": "DomainId",
    "query": "hsc,eng,mat,jhs,pri,man,lan,api,cmp"
   },
   { "name": "NodeId", "query": "01,02,03,04" },
   {
    "name": "host",
    "label": "Host Name",
    "query": "show tag values from \"cpu\" with key = \"host\" where \"host\" =~ /$ServerType/  and \"host\" =~ /$DomainId/ and \"host\" =~ /$NodeId/ "
   },
   {
    "name": "nics",
    "label": "Network Card",
    "query": "show tag values from \"net\" with key = \"interface\" "
   },
   {
    "name": "disks",
    "label": "Hard Disk",
    "query": "show tag values from \"disk\" with key = \"device\""
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Total",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "cpu",
       "query": "SELECT mean(\"User%\") + mean(\"Sys%\") + mean(\"Wait%\") AS \"Total\", mean(\"User%\") AS \"User\", mean(\"Sys%\") AS \"System\", mean(\"Wait%\") AS \"Wait\" FROM \"CPU_ALL\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time(3s)",
       "select": [
        [
         { "params": [ "usage_user" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "User" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_system" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "System" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_iowait" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Wait" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_steal" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Steal" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "system",
       "query": "SELECT 100 - mean(\"Idle%\") AS \" \"  FROM \"CPU\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"id\"",
       "select": [
        [
         { "params": [ "n_cpus" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "n_cpus" ], "type": "alias" }
        ],
        [
         { "params": [ "n_users" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "n_users" ], "type": "alias" }
        ],
        [
         { "params": [ "load1" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "load1" ], "type": "alias" }
        ],
        [
         { "params": [ "load5" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "load5" ], "type": "alias" }
        ],
        [
         { "params": [ "load15" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "load15" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Running/Blocked/Sleeping/Dead",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "Runnable" }
     ],
     "targets": [
      {
       "alias": "$col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "processes",
       "select": [
        [
         { "params": [ "running" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Runnable" ], "type": "alias" }
        ],
        [
         { "params": [ "dead" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Dead" ], "type": "alias" }
        ],
        [
         { "params": [ "blocked" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Blocked" ], "type": "alias" }
        ],
        [
         { "params": [ "sleeping" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Sleeping" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Linux Kernel - Context Switch/Interrupt",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "kernel",
       "query": "SELECT mean(\"Process%\") AS \"Process\", mean(\"System%\") AS \"System\", mean(\"Free%\") AS \"Free\" FROM \"MEMNEW\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "context_switches" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ "ContestSwich" ], "type": "alias" }
        ],
        [
         { "params": [ "interrupts" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ "Interrupt" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Paging/Zombies/Total/TotalThreads",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Paging" }
     ],
     "targets": [
      {
       "alias": "$col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "processes",
       "select": [
        [
         { "params": [ "paging" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Paging" ], "type": "alias" }
        ],
        [
         { "params": [ "zombies" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Zombies" ], "type": "alias" }
        ],
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Total" ], "type": "alias" }
        ],
        [
         { "params": [ "total_threads" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Thread" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Linux Kernel",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "kernel",
       "query": "SELECT mean(\"Process%\") AS \"Process\", mean(\"System%\") AS \"System\", mean(\"Free%\") AS \"Free\" FROM \"MEMNEW\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "entropy_avail" ], "type": "field" },
         {
          "params": [],
          "type": "stddev"
         },
         { "params": [ "Entropy" ], "type": "alias" }
        ],
        [
         { "params": [ "processes_forked" ], "type": "field" },
         {
          "params": [],
          "type": "stddev"
         },
         { "params": [ "Fork" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Physical Memory",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 20 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "mem",
       "query": "SELECT mean(\"memtotal\") FROM \"MEM\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Total" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Physical Memory Used",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 20 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "mem",
       "query": "SELECT mean(\"memtotal\") - mean(\"memfree\")  FROM \"MEM\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Used" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Physical Memory Free",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 20 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "mem",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Paging/Zombies/Total/TotalThreads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "mem",
       "select": [
        [
         { "params": [ "inactive" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Inactive" ], "type": "alias" }
        ],
        [
         { "params": [ "active" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Active" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Total PageSwap Space",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 28 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "mem",
       "query": "SELECT mean(\"swaptotal\") FROM \"MEM\" WHERE  (\"host\" =~ /^$host$/)  AND $timeFilter GROUP BY time(3s) fill(null)",
       "select": [
        [
         { "params": [ "swap_total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "PageSwap Space Used",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 28 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "mem",
       "query": "SELECT mean(\"swap_total\") - mean(\"swap_free\") FROM \"mem\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "swap_total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "PageSwap Space Free",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 28 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "mem",
       "select": [
        [
         { "params": [ "swap_free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Paging/Zombies/Total/TotalThreads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 28 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "mem",
       "select": [
        [
         { "params": [ "slab" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Slab" ], "type": "alias" }
        ],
        [
         { "params": [ "cached" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Cached" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Network I/O - $nics",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_host $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT non_negative_difference(mean(\"bytes_recv\")) / 2 AS \"Rx KB/s\", non_negative_difference(mean(\"bytes_sent\")) / 2 AS \"Tx KB/s\" FROM \"net\" WHERE (\"host\" =~ /^$host$/ AND \"interface\" =~ /^$nics$/) AND $timeFilter GROUP BY time($__interval), \"host\"",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ " / 2" ], "type": "math" },
       { "params": [ "Rx KB/s" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ " / 2" ], "type": "math" },
       { "params": [ "Tx KB/s" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$nics$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Packets - $nics",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"read/s\") AS \"Read\", mean(\"write/s\") AS \"Write\" FROM \"NETPACKET\" WHERE (\"host\"  =~ /^$host$/ AND \"id\" =~ /^$nics$/) AND $timeFilter GROUP BY time($__interval), \"id\"",
     "select": [
      [
       { "params": [ "packets_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "PacketRx" ], "type": "alias" }
      ],
      [
       { "params": [ "packets_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "PacketTx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$nics$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Status",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "netstat",
     "query": "SELECT mean(\"read/s\") AS \"Read\", mean(\"write/s\") AS \"Write\" FROM \"NETPACKET\" WHERE (\"host\"  =~ /^$host$/ AND \"id\" =~ /^$nics$/) AND $timeFilter GROUP BY time($__interval), \"id\"",
     "select": [
      [
       { "params": [ "tcp_close_wait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "CloseWait" ], "type": "alias" }
      ],
      [
       { "params": [ "tcp_established" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Established" ], "type": "alias" }
      ],
      [
       { "params": [ "tcp_listen" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Listen" ], "type": "alias" }
      ],
      [
       { "params": [ "tcp_time_wait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "TimeWait" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Drop",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"read/s\") AS \"Read\", mean(\"write/s\") AS \"Write\" FROM \"NETPACKET\" WHERE (\"host\"  =~ /^$host$/ AND \"id\" =~ /^$nics$/) AND $timeFilter GROUP BY time($__interval), \"id\"",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "DropIn" ], "type": "alias" }
      ],
      [
       { "params": [ "drop_out" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "DropOut" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Error",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"read/s\") AS \"Read\", mean(\"write/s\") AS \"Write\" FROM \"NETPACKET\" WHERE (\"host\"  =~ /^$host$/ AND \"id\" =~ /^$nics$/) AND $timeFilter GROUP BY time($__interval), \"id\"",
     "select": [
      [
       { "params": [ "err_in" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "ErrorIn" ], "type": "alias" }
      ],
      [
       { "params": [ "err_out" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "ErrorOut" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Udp",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "netstat",
     "query": "SELECT mean(\"read-KB/s\") AS \"Read-KB/s\", mean(\"write-KB/s\") AS \"Write-KB/s\" FROM \"NET\" WHERE (\"host\"  =~ /^$host$/ AND \"id\" =~ /^$nics$/) AND $timeFilter GROUP BY time($__interval), \"id\"",
     "select": [
      [
       { "params": [ "udp_socket" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "UdpSocket" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "DISK I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Read KB/s - $disks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "diskio",
       "query": "SELECT mean(\"value\") FROM \"DISKREAD\" WHERE (\"host\"  =~ /^$host$/ AND \"id\" =~ /^$disks$/ AND \"id\" != 'cd0') AND $timeFilter GROUP BY time($__interval), \"id\"",
       "select": [
        [
         { "params": [ "read_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "stddev"
         },
         { "params": [ "Read KB/s" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$disks$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk Write KB/s - $disks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "diskio",
       "query": "SELECT mean(\"value\") FROM \"DISKWRITE\" WHERE (\"host\"  =~ /^$host$/ AND \"id\" =~ /^$disks$/ AND \"id\" != 'cd0') AND $timeFilter GROUP BY time($__interval), \"id\"",
       "select": [
        [
         { "params": [ "write_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "stddev"
         },
         { "params": [ "Write KB/s" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$disks$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk IOPS - $disks",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "diskio",
       "query": "SELECT mean(\"value\") FROM \"DISKXFER\" WHERE (\"host\"  =~ /^$host$/ AND \"id\" =~ /^$disks$/ AND \"id\" != 'cd0') AND $timeFilter GROUP BY time($__interval), \"id\"",
       "select": [
        [
         { "params": [ "iops_in_progress" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "IOPS" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$disks$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk Busy - $disks",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "alias": "$col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "diskio",
       "query": "SELECT mean(\"value\") FROM \"DISKBUSY\" WHERE (\"host\"  =~ /^$host$/ AND \"id\" =~ /^$disks$/ AND \"id\" != 'cd0') AND $timeFilter GROUP BY time($__interval), \"id\"",
       "select": [
        [
         { "params": [ "read_time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Read Time" ], "type": "alias" }
        ],
        [
         { "params": [ "write_time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Write Time" ], "type": "alias" }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "File Systems Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Filespace %Used",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "alias": "$tag_path $col",
       "function": "mean",
       "groupBy": [
        { "params": [ "5m" ], "type": "time" },
        { "params": [ "path" ], "type": "tag" }
       ],
       "groupByTags": [ "name" ],
       "measurement": "disk",
       "query": "SELECT mean(\"value\") FROM \"JFSFILE\" WHERE (\"host\" =~ /^$host$/ AND \"id\" <> '/var/adm/ras/livedump' AND \"id\" <> '/var/adm/ras/platform') AND $timeFilter GROUP BY time(5m), \"id\"",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Total GB" ], "type": "alias" }
        ]
       ],
       "transform": "timeseries_to_columns"
      },
      {
       "alias": "$tag_path $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"used\") / mean(\"total\")  as \"Used%\" FROM \"disk\" WHERE $timeFilter GROUP BY time(5m), \"path\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}