{
 "title": "SDE Server Group Trend - OverAll",
 "description": "InfluxDB dashboards for telegraf metrics",
 "time": { "from": "2021-04-10T05:25:01.316Z", "to": "2021-04-10T05:41:21.437Z" },
 "templating": {
  "list": [
   {
    "name": "domainId",
    "label": "도메인",
    "query": "hsc,eng,mat,jhs,pri,man,lan,api,cmp"
   },
   {
    "name": "bizType",
    "label": "업무구분",
    "query": "SHOW TAG VALUES FROM system WITH KEY= host where host =~ /-was-/ and host =~ /$domainId/"
   },
   {
    "name": "web",
    "label": "Web Server",
    "query": "SHOW TAG VALUES FROM system WITH KEY= host where host =~ /-web-/ and host =~ /$domainId-$bizType/"
   },
   {
    "name": "was",
    "label": "WAS Server",
    "query": "SHOW TAG VALUES FROM system WITH KEY= host where host =~ /-was-/ and host =~ /$domainId-$bizType/"
   },
   {
    "name": "webNodeId",
    "query": "SHOW TAG VALUES FROM system WITH KEY= host where host =~ /-web-/ and host =~ /$bizType/"
   },
   {
    "name": "wasNodeId",
    "query": "SHOW TAG VALUES FROM system WITH KEY= host where host =~ /-was-/ and host =~ /$bizType/"
   },
   { "name": "redis", "label": "Redis Server", "query": "cmp,hsc" },
   { "name": "inter", "label": "Interval", "query": "5s,10s,30s,1m,2m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "$domainId - Overall Current Status ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Web Server $domainId - $bizType",
     "type": "mxswat-separator-panel",
     "gridPos": { "h": 1, "w": 6, "x": 0, "y": 1 }
    },
    {
     "title": "WAS Server $domainId - $bizType",
     "type": "mxswat-separator-panel",
     "gridPos": { "h": 1, "w": 6, "x": 6, "y": 1 }
    },
    { "title": "Redis Server ", "type": "mxswat-separator-panel", "gridPos": { "h": 1, "w": 6, "x": 12, "y": 1 } },
    { "title": "MaxScale Server $domainId", "type": "mxswat-separator-panel", "gridPos": { "h": 1, "w": 6, "x": 18, "y": 1 } },
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_host $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "cpu",
       "query": "SELECT 100 - mean(\"usage_idle\") AS \"Cpu\" FROM \"cpu\" WHERE (\"host\" =~ /^$web$/ AND \"host\" =~ /$webNodeId/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
       "select": [
        [
         { "params": [ "usage_user" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "user" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_system" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "system" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_steal" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "steal" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$web$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$webNodeId/" }
       ]
      }
     ]
    },
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 2 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_host $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "cpu",
       "query": "SELECT 100 - mean(\"usage_idle\") AS \"Cpu\" FROM \"cpu\" WHERE (\"host\" =~ /^$was$/ AND \"host\" =~ /$wasNodeId/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
       "select": [
        [
         { "params": [ "usage_user" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "user" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_system" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "system" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_steal" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "steal" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$web$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$webNodeId/" }
       ]
      }
     ]
    },
    {
     "title": "CPU Session Store - $redis",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_host $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpu",
       "query": "SELECT 100 - mean(\"usage_idle\") as \"Cpu\" FROM \"cpu\" WHERE host =~ /$redis-redis-sto/  AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
       "select": [
        [
         { "params": [ "usage_user" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "user" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_system" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "system" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_steal" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "steal" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$web$/" }
       ]
      }
     ]
    },
    {
     "title": "CPU ",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_host $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpu",
       "query": "SELECT 100 - mean(\"usage_idle\") FROM \"cpu\" WHERE \"host\" =~ /-max-/ and host =~ /$domainId/  AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
       "select": [
        [
         { "params": [ "usage_user" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "user" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_system" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "system" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_steal" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "steal" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$web$/" }
       ]
      }
     ]
    },
    {
     "title": "ContextSwitch",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_host $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "kernel",
       "query": "SELECT mean(usage_user) + mean(usage_system) as \"Usage\"  FROM \"cpu\" WHERE \"host\" =~ /$server$/ and  cpu = 'cpu-total' AND $timeFilter GROUP BY time($__interval), *",
       "select": [
        [
         { "params": [ "context_switches" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "ContextSwitch" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$web$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$webNodeId$/" }
       ]
      }
     ]
    },
    {
     "title": "ContextSwitch",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_host $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "kernel",
       "query": "SELECT mean(usage_user) + mean(usage_system) as \"Usage\"  FROM \"cpu\" WHERE \"host\" =~ /$server$/ and  cpu = 'cpu-total' AND $timeFilter GROUP BY time($__interval), *",
       "select": [
        [
         { "params": [ "context_switches" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "ContextSwitch" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$was$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$wasNodeId/" }
       ]
      }
     ]
    },
    {
     "title": "ContextSwitch Session Store - $redis",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_host $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "kernel",
       "query": "SELECT mean(usage_user) + mean(usage_system) as \"Usage\"  FROM \"cpu\" WHERE \"host\" =~ /$server$/ and  cpu = 'cpu-total' AND $timeFilter GROUP BY time($__interval), *",
       "select": [
        [
         { "params": [ "context_switches" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "ContextSwitch" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/$redis-redis-sto/" }
       ]
      }
     ]
    },
    {
     "title": "ContextSwitch",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_host $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "kernel",
       "query": "SELECT mean(usage_user) + mean(usage_system) as \"Usage\"  FROM \"cpu\" WHERE \"host\" =~ /$server$/ and  cpu = 'cpu-total' AND $timeFilter GROUP BY time($__interval), *",
       "select": [
        [
         { "params": [ "context_switches" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "ContextSwitch" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/-max-/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$domainId/" }
       ]
      }
     ]
    },
    {
     "title": "Interrupts",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_host $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "kernel",
       "query": "SELECT mean(usage_user) + mean(usage_system) as \"Usage\"  FROM \"cpu\" WHERE \"host\" =~ /$server$/ and  cpu = 'cpu-total' AND $timeFilter GROUP BY time($__interval), *",
       "select": [
        [
         { "params": [ "interrupts" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "Interrupts" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$web$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$webNodeId/" }
       ]
      }
     ]
    },
    {
     "title": "Interrupts",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_host $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "kernel",
       "query": "SELECT mean(usage_user) + mean(usage_system) as \"Usage\"  FROM \"cpu\" WHERE \"host\" =~ /$server$/ and  cpu = 'cpu-total' AND $timeFilter GROUP BY time($__interval), *",
       "select": [
        [
         { "params": [ "interrupts" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "Interrupts" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$was$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$wasNodeId/" }
       ]
      }
     ]
    },
    {
     "title": "Interrupts - $redis",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_host $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "kernel",
       "query": "SELECT mean(usage_user) + mean(usage_system) as \"Usage\"  FROM \"cpu\" WHERE \"host\" =~ /$server$/ and  cpu = 'cpu-total' AND $timeFilter GROUP BY time($__interval), *",
       "select": [
        [
         { "params": [ "interrupts" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "Interrupts" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/$redis-redis-sto/" }
       ]
      }
     ]
    },
    {
     "title": "Network ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
        { "key": "host", "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "net",
       "query": "SELECT non_negative_derivative(mean(bytes_recv),1s) as \"in\" FROM \"net\" WHERE host =~ /$web/ AND interface =~ /(vlan|eth|bond).*/ AND $timeFilter GROUP BY time($__interval), * fill(none)",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "out" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "in" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/-max-/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$domainId/" },
        { "condition": "AND", "key": "interface", "operator": "=", "value": "eth0" }
       ]
      }
     ]
    },
    {
     "title": "Network ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
        { "key": "host", "params": [ "host" ], "type": "tag" }
       ],
       "measurement": "net",
       "query": "SELECT non_negative_derivative(mean(bytes_recv),1s) as \"in\" FROM \"net\" WHERE host =~ /$web/ AND interface =~ /(vlan|eth|bond).*/ AND $timeFilter GROUP BY time($__interval), * fill(none)",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "out" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "in" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$web$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$domainId/" },
        { "condition": "AND", "key": "interface", "operator": "=", "value": "eth0" }
       ]
      }
     ]
    },
    {
     "title": "Network ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$tag_host $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
        { "key": "host", "params": [ "host" ], "type": "tag" },
        { "params": [ "interface" ], "type": "tag" }
       ],
       "measurement": "net",
       "query": "SELECT non_negative_derivative(mean(bytes_recv),1s) as \"in\" FROM \"net\" WHERE host =~ /$web/ AND interface =~ /(vlan|eth|bond).*/ AND $timeFilter GROUP BY time($__interval), * fill(none)",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "out" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "in" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$was$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$wasNodeId/" },
        { "condition": "AND", "key": "interface", "operator": "=", "value": "eth0" }
       ]
      }
     ]
    },
    {
     "title": "Network Session Store - $redis",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
        { "key": "host", "params": [ "host" ], "type": "tag" },
        { "params": [ "interface" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "net",
       "query": "SELECT non_negative_derivative(mean(bytes_recv),1s) as \"in\" FROM \"net\" WHERE host =~ /$web/ AND interface =~ /(vlan|eth|bond).*/ AND $timeFilter GROUP BY time($__interval), * fill(none)",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "out" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "in" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/$redis-redis-sto/" },
        { "condition": "AND", "key": "interface", "operator": "=", "value": "eth0" }
       ]
      }
     ]
    },
    {
     "title": "Network Packets",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "alias": "$tag_host $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
        { "key": "host", "params": [ "host" ], "type": "tag" },
        { "params": [ "interface" ], "type": "tag" }
       ],
       "measurement": "net",
       "query": "SELECT non_negative_derivative(mean(bytes_recv),1s) as \"in\" FROM \"net\" WHERE host =~ /$web/ AND interface =~ /(vlan|eth|bond).*/ AND $timeFilter GROUP BY time($__interval), * fill(none)",
       "select": [
        [
         { "params": [ "packets_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "out" ], "type": "alias" }
        ],
        [
         { "params": [ "packets_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "in" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/-max-/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$domainId/" },
        { "condition": "AND", "key": "interface", "operator": "=", "value": "eth0" }
       ]
      }
     ]
    },
    {
     "title": "Network Packets",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "alias": "$tag_host $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
        { "key": "host", "params": [ "host" ], "type": "tag" }
       ],
       "measurement": "net",
       "query": "SELECT non_negative_derivative(mean(bytes_recv),1s) as \"in\" FROM \"net\" WHERE host =~ /$web/ AND interface =~ /(vlan|eth|bond).*/ AND $timeFilter GROUP BY time($__interval), * fill(none)",
       "select": [
        [
         { "params": [ "packets_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "out" ], "type": "alias" }
        ],
        [
         { "params": [ "packets_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "in" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$web$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$domainId/" },
        { "condition": "AND", "key": "interface", "operator": "=", "value": "eth0" }
       ]
      }
     ]
    },
    {
     "title": "Network Packets",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "alias": "$tag_host $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
        { "key": "host", "params": [ "host" ], "type": "tag" },
        { "params": [ "interface" ], "type": "tag" }
       ],
       "measurement": "net",
       "query": "SELECT non_negative_derivative(mean(bytes_recv),1s) as \"in\" FROM \"net\" WHERE host =~ /$web/ AND interface =~ /(vlan|eth|bond).*/ AND $timeFilter GROUP BY time($__interval), * fill(none)",
       "select": [
        [
         { "params": [ "packets_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "out" ], "type": "alias" }
        ],
        [
         { "params": [ "packets_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "in" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$was$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$wasNodeId/" },
        { "condition": "AND", "key": "interface", "operator": "=", "value": "eth0" }
       ]
      }
     ]
    },
    {
     "title": "Network Data Cache - $redis",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
        { "key": "host", "params": [ "host" ], "type": "tag" },
        { "params": [ "interface" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "net",
       "query": "SELECT non_negative_derivative(mean(bytes_recv),1s) as \"in\" FROM \"net\" WHERE host =~ /$web/ AND interface =~ /(vlan|eth|bond).*/ AND $timeFilter GROUP BY time($__interval), * fill(none)",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "out" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "in" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/$redis-redis-dat/" },
        { "condition": "AND", "key": "interface", "operator": "=", "value": "eth0" }
       ]
      }
     ]
    },
    {
     "title": "TCP Status - $wasNodeId",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "netstat",
       "select": [
        [
         { "params": [ "tcp_close_wait" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "CloseWait" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_established" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Established" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_listen" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Listen" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_close" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Close" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_time_wait" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "TimeWait" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_fin_wait1" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "FinWait1" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_fin_wait2" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "FinWait2" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_last_ack" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "LastAck" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_syn_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "SynRecv" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_syn_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "SynSent" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/-max-/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$domainId/" }
       ]
      }
     ]
    },
    {
     "title": "Workers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "apache",
       "select": [
        [
         { "params": [ "IdleWorkers" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Idle" ], "type": "alias" }
        ],
        [
         { "params": [ "BusyWorkers" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Busy" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$web$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$webNodeId$/" }
       ]
      }
     ]
    },
    {
     "title": "TCP Status - $wasNodeId",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 36 },
     "repeat": "wasNodeId",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "netstat",
       "select": [
        [
         { "params": [ "tcp_close_wait" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "CloseWait" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_established" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Established" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_listen" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Listen" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_close" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Close" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_time_wait" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "TimeWait" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_fin_wait1" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "FinWait1" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_fin_wait2" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "FinWait2" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_last_ack" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "LastAck" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_syn_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "SynRecv" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_syn_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "SynSent" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$was$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$wasNodeId/" }
       ]
      }
     ]
    },
    {
     "title": "Operations/sec  Session Store - $redis",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "$tag_host $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "redis",
       "select": [
        [
         { "params": [ "instantaneous_ops_per_sec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Ops" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/$redis-redis-sto/" }
       ]
      }
     ]
    },
    { "title": "DBMS Server $domainId", "type": "mxswat-separator-panel", "gridPos": { "h": 1, "w": 6, "x": 18, "y": 38 } },
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_host $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpu",
       "query": "SELECT 100 - mean(\"usage_idle\") FROM \"cpu\" WHERE \"host\" =~ /-db-/ and host =~ /$domainId/  AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
       "select": [
        [
         { "params": [ "usage_user" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "user" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_system" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "system" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_steal" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "steal" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$web$/" }
       ]
      }
     ]
    },
    {
     "title": "Operations/sec  Data Cache - $redis",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "$tag_host $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "redis",
       "select": [
        [
         { "params": [ "instantaneous_ops_per_sec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Ops" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/$redis-redis-dat/" }
       ]
      }
     ]
    },
    {
     "title": "Accesses / Second",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "apache",
       "select": [
        [
         { "params": [ "TotalAccesses" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "TotalAccess" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$web$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$webNodeId$/" }
       ]
      }
     ]
    },
    {
     "title": "TCP Status - $wasNodeId",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "netstat",
       "select": [
        [
         { "params": [ "tcp_close_wait" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "CloseWait" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_established" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Established" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_listen" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Listen" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_close" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Close" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_time_wait" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "TimeWait" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_fin_wait1" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "FinWait1" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_fin_wait2" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "FinWait2" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_last_ack" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "LastAck" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_syn_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "SynRecv" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_syn_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "SynSent" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$was$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$wasNodeId/" }
       ]
      }
     ]
    },
    {
     "title": "ContextSwitch - ",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_host $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "kernel",
       "query": "SELECT mean(usage_user) + mean(usage_system) as \"Usage\"  FROM \"cpu\" WHERE \"host\" =~ /$server$/ and  cpu = 'cpu-total' AND $timeFilter GROUP BY time($__interval), *",
       "select": [
        [
         { "params": [ "context_switches" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "ContextSwitch" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/-db-/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$domainId/" }
       ]
      }
     ]
    },
    {
     "title": "Session Store - cmp",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "command": "info", "section": "stats", "type": "command" }
     ]
    },
    {
     "title": "Session Store - hsc",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 15, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "command": "info", "section": "stats", "type": "command" }
     ]
    },
    {
     "title": "Requests Per Second ",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "apache",
       "select": [
        [
         { "params": [ "ReqPerSec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Rps" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$web$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$webNodeId$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Session Store - cmp",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "command": "info", "section": "stats", "type": "command" }
     ]
    },
    {
     "title": "Network Session Store - hsc",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 15, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "command": "info", "section": "stats", "type": "command" }
     ]
    },
    {
     "title": "Network ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
        { "key": "host", "params": [ "host" ], "type": "tag" }
       ],
       "measurement": "net",
       "query": "SELECT non_negative_derivative(mean(bytes_recv),1s) as \"in\" FROM \"net\" WHERE host =~ /$web/ AND interface =~ /(vlan|eth|bond).*/ AND $timeFilter GROUP BY time($__interval), * fill(none)",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "out" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "in" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/-db-/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$domainId/" },
        { "condition": "AND", "key": "interface", "operator": "=", "value": "eth0" }
       ]
      }
     ]
    },
    {
     "title": "Processes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_host $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "processes",
       "query": "SELECT 100 - mean(\"usage_idle\") FROM \"cpu\" WHERE (\"host\" =~ /$was/) AND (\"host\" =~ /$wasNodeId/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "processes" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$was$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$wasNodeId$/" }
       ]
      }
     ]
    },
    {
     "title": "Cmp Session Store Clients",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 12, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "command": "info", "section": "clients", "type": "command" }
     ]
    },
    {
     "title": "Hsc Session Store Clients",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 15, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "command": "info", "section": "clients", "type": "command" }
     ]
    },
    {
     "title": "Bytes per Requests",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "apache",
       "select": [
        [
         { "params": [ "BytesPerReq" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Bpr" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$web$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$webNodeId$/" }
       ]
      }
     ]
    },
    {
     "title": "Cmp Session Store Keys",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "query": "dbsize", "section": "clients", "type": "cli" }
     ]
    },
    {
     "title": "Hsc Session Store Keys",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 15, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "query": "dbsize", "section": "stats", "type": "cli" }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_host $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "processes",
       "query": "SELECT 100 - mean(\"usage_idle\") FROM \"cpu\" WHERE (\"host\" =~ /$was/) AND (\"host\" =~ /$wasNodeId/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "total_threads" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Threads" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$was$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$wasNodeId$/" }
       ]
      }
     ]
    },
    {
     "title": "Memory Session Store - cmp",
     "type": "bargauge",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "command": "info", "section": "memory", "type": "command" }
     ]
    },
    {
     "title": "Memory Session Store - hsc",
     "type": "bargauge",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "command": "info", "section": "memory", "type": "command" }
     ]
    },
    {
     "title": "Queries",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 59 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_host",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "SELECT mean(usage_user) + mean(usage_system) as \"Usage\"  FROM \"cpu\" WHERE \"host\" =~ /$server$/ and  cpu = 'cpu-total' AND $timeFilter GROUP BY time($__interval), *",
       "select": [
        [
         { "params": [ "queries" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/-db-/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$domainId/" }
       ]
      }
     ]
    },
    {
     "title": "Bytes per Seconds",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "apache",
       "select": [
        [
         { "params": [ "BytesPerSec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Bps" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$web$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$webNodeId$/" }
       ]
      }
     ]
    },
    {
     "title": "Data Cache - cmp",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 12, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "command": "info", "section": "stats", "type": "command" }
     ]
    },
    {
     "title": "Data Cache - hsc",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 15, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "command": "info", "section": "stats", "type": "command" }
     ]
    },
    {
     "title": "MySQL Traffic",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_host $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
        { "key": "host", "params": [ "host" ], "type": "tag" }
       ],
       "measurement": "mysql",
       "query": "SELECT non_negative_derivative(mean(bytes_recv),1s) as \"in\" FROM \"net\" WHERE host =~ /$web/ AND interface =~ /(vlan|eth|bond).*/ AND $timeFilter GROUP BY time($__interval), * fill(none)",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ "out" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_received" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ "in" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/-db-/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$domainId/" }
       ]
      }
     ]
    },
    {
     "title": "Network Session Store - cmp",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "command": "info", "section": "stats", "type": "command" }
     ]
    },
    {
     "title": "Network Session Store - hsc",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 15, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "command": "info", "section": "stats", "type": "command" }
     ]
    },
    {
     "title": "Forks ",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 66 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "kernel",
       "select": [
        [
         { "params": [ "processes_forked" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "Fork" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$was$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$wasNodeId$/" }
       ]
      }
     ]
    },
    {
     "title": "TCP Status - $webNodeId",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 68 },
     "repeat": "webNodeId",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "netstat",
       "select": [
        [
         { "params": [ "tcp_close_wait" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "CloseWait" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_established" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Established" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_listen" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Listen" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_close" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Close" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_time_wait" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "TimeWait" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_fin_wait1" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "FinWait1" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_fin_wait2" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "FinWait2" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_last_ack" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "LastAck" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_syn_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "SynRecv" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_syn_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "SynSent" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$web$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$webNodeId/" }
       ]
      }
     ]
    },
    {
     "title": "Memory Session Store - cmp",
     "type": "bargauge",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "command": "info", "section": "memory", "type": "command" }
     ]
    },
    {
     "title": "Memory Data Cache - hsc",
     "type": "bargauge",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "command": "info", "section": "memory", "type": "command" }
     ]
    },
    {
     "title": "Slow Queries",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 71 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_host",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "SELECT mean(usage_user) + mean(usage_system) as \"Usage\"  FROM \"cpu\" WHERE \"host\" =~ /$server$/ and  cpu = 'cpu-total' AND $timeFilter GROUP BY time($__interval), *",
       "select": [
        [
         { "params": [ "slow_queries" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/-db-/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$domainId/" }
       ]
      }
     ]
    },
    {
     "title": "Cmp Session Store Clients",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 12, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "command": "info", "section": "clients", "type": "command" }
     ]
    },
    {
     "title": "Hsc Session Store Clients",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 15, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "command": "info", "section": "clients", "type": "command" }
     ]
    },
    {
     "title": "Cmp Session Store Keys",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 12, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "query": "dbsize", "section": "clients", "type": "cli" }
     ]
    },
    {
     "title": "Hsc Session Store Keys",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 15, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "query": "dbsize", "section": "stats", "type": "cli" }
     ]
    },
    {
     "title": "Active Threads",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_host $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "$__interval" ], "type": "time" },
        { "key": "host", "params": [ "host" ], "type": "tag" },
        { "params": [ "interface" ], "type": "tag" }
       ],
       "measurement": "mysql",
       "query": "SELECT non_negative_derivative(mean(bytes_recv),1s) as \"in\" FROM \"net\" WHERE host =~ /$web/ AND interface =~ /(vlan|eth|bond).*/ AND $timeFilter GROUP BY time($__interval), * fill(none)",
       "select": [
        [
         { "params": [ "threads_connected" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Connected" ], "type": "alias" }
        ],
        [
         { "params": [ "threads_running" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Running" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/-db-/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$domainId/" }
       ]
      }
     ]
    },
    {
     "title": "TCP Status - $webNodeId",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "netstat",
       "select": [
        [
         { "params": [ "tcp_close_wait" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "CloseWait" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_established" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Established" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_listen" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Listen" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_close" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Close" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_time_wait" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "TimeWait" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_fin_wait1" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "FinWait1" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_fin_wait2" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "FinWait2" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_last_ack" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "LastAck" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_syn_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "SynRecv" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_syn_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "SynSent" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$web$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$webNodeId/" }
       ]
      }
     ]
    },
    {
     "title": "Processes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_host $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "processes",
       "query": "SELECT 100 - mean(\"usage_idle\") FROM \"cpu\" WHERE (\"host\" =~ /$was/) AND (\"host\" =~ /$wasNodeId/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "processes" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$web$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$webNodeId/" }
       ]
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_host $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "processes",
       "query": "SELECT 100 - mean(\"usage_idle\") FROM \"cpu\" WHERE (\"host\" =~ /$was/) AND (\"host\" =~ /$wasNodeId/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
       "select": [
        [
         { "params": [ "total_threads" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Threads" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$web$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$webNodeId/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "$domainId - File & Disk IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Web Server $domainId - $bizType",
     "type": "mxswat-separator-panel",
     "gridPos": { "h": 1, "w": 6, "x": 0, "y": 2 }
    },
    {
     "title": "WAS Server $domainId - $bizType",
     "type": "mxswat-separator-panel",
     "gridPos": { "h": 1, "w": 6, "x": 6, "y": 2 }
    },
    { "title": "Redis Server $domainId", "type": "mxswat-separator-panel", "gridPos": { "h": 1, "w": 6, "x": 12, "y": 2 } },
    { "title": "DBMS Server $domainId", "type": "mxswat-separator-panel", "gridPos": { "h": 1, "w": 6, "x": 18, "y": 2 } },
    {
     "title": "File",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_host $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "linux_sysctl_fs",
       "select": [
        [
         { "params": [ "file-nr" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "File-nr" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$web$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$domainId/" }
       ]
      }
     ]
    },
    {
     "title": "File",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_host $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "linux_sysctl_fs",
       "select": [
        [
         { "params": [ "file-nr" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "File-nr" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$was$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$domainId/" }
       ]
      }
     ]
    },
    {
     "title": "File",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_host $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "linux_sysctl_fs",
       "select": [
        [
         { "params": [ "file-nr" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "File-nr" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/-redis-/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$domainId/" }
       ]
      }
     ]
    },
    {
     "title": "File",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_host $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "linux_sysctl_fs",
       "select": [
        [
         { "params": [ "file-nr" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "File-nr" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/-db-/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$domainId/" }
       ]
      }
     ]
    },
    {
     "title": "Disk I/O bytes",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "decbits" } },
     "yaxes": [
      { "format": "decbits" }
     ],
     "targets": [
      {
       "alias": "$tag_host $tag_name $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "write_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "write" ], "type": "alias" }
        ],
        [
         { "params": [ "read_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "read" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$web$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$domainId/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/xvd[a|b]$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk I/O bytes",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "decbits" } },
     "yaxes": [
      { "format": "decbits" }
     ],
     "targets": [
      {
       "alias": "$tag_host $tag_name $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "write_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "write" ], "type": "alias" }
        ],
        [
         { "params": [ "read_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "read" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$was$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$domainId/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/xvd[a|b]$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk I/O bytes",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "decbits" } },
     "yaxes": [
      { "format": "decbits" }
     ],
     "targets": [
      {
       "alias": "$tag_host $tag_name $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "write_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "write" ], "type": "alias" }
        ],
        [
         { "params": [ "read_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "read" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/-redis-/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$domainId/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/xvd[a|b]$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk I/O bytes",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "decbits" } },
     "yaxes": [
      { "format": "decbits" }
     ],
     "targets": [
      {
       "alias": "$tag_host $tag_name $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "write_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "write" ], "type": "alias" }
        ],
        [
         { "params": [ "read_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "read" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/-db-/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$domainId/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/xvd[a|b]$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk I/O requests",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host $tag_name $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "writes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "write" ], "type": "alias" }
        ],
        [
         { "params": [ "reads" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "read" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$web$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$domainId/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/xvd[a|b]$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk I/O requests",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host $tag_name $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "writes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "write" ], "type": "alias" }
        ],
        [
         { "params": [ "reads" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "read" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$was$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$domainId/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/xvd[a|b]$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk I/O requests",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host $tag_name $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "writes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "write" ], "type": "alias" }
        ],
        [
         { "params": [ "reads" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "read" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/-redis-/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$domainId/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/xvd[a|b]$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk I/O requests",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host $tag_name $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "writes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "write" ], "type": "alias" }
        ],
        [
         { "params": [ "reads" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "read" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/-db-/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/$domainId/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/xvd[a|b]$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}