---
telegraf_enabled: True
# defaults file for ansible-telegraf

telegraf_agent_version: 1.18.0
telegraf_agent_version_patch: 1
telegraf_agent_package: telegraf
telegraf_agent_package_file_deb: telegraf_{{ telegraf_agent_version }}-{{ telegraf_agent_version_patch }}_{{ telegraf_agent_package_arch }}.deb
telegraf_agent_package_file_rpm: telegraf-{{ telegraf_agent_version }}-{{ telegraf_agent_version_patch }}.{{ ansible_architecture }}.rpm
telegraf_agent_package_path: /tmp
telegraf_agent_package_method: repo
telegraf_agent_package_state: present
telegraf_agent_hostname: "{{ ansible_fqdn }}"
telegraf_agent_interval: 5
telegraf_agent_debug: False
telegraf_agent_round_interval: True
telegraf_agent_flush_interval: 10
telegraf_agent_flush_jitter: 0
telegraf_agent_aws_tags: False
telegraf_agent_aws_tags_prefix: ""
telegraf_agent_config_path: /etc/telegraf

# Docker specific settings
telegraf_uid_docker: 998
telegraf_gid_docker: 995
telegraf_agent_docker: False
telegraf_agent_docker_name: telegraf
telegraf_agent_docker_network_mode: bridge
telegraf_agent_docker_restart_policy: unless-stopped

# v0.13 settings (not sure if supported in older version):
telegraf_agent_collection_jitter: 0
telegraf_agent_metric_batch_size: 1000
telegraf_agent_metric_buffer_limit: 10000
telegraf_agent_quiet: False

# v1.1 settings:
telegraf_agent_logfile: ""
telegraf_agent_omit_hostname: False

telegraf_global_tags: []

telegraf_agent_output:
  - type: influxdb
    config:
      - urls = ["udp://172.23.2.11:8089"]
      - database = "TELEGRAF"
      # - precision = "s"

# defaults - /etc/telegraf/telegraf.conf
telegraf_plugins_default:      
  - plugin: cpu
    config:
      - percpu = true
  - plugin: interrupts
  - plugin: disk
  - plugin: io
  - plugin: mem
  - plugin: net
  - plugin: system
  - plugin: swap
  - plugin: netstat
  - plugin: processes
  - plugin: kernel
  - plugin: nstat
  - plugin: linux_sysctl_fs
#  - plugin: conntrack
  - plugin: internal

# redis standalone
telegraf_plugins_redis:
  - plugin: redis
    config:
      - servers = ["tcp://127.0.0.1:6382"]

# redis cluster
telegraf_plugins_redis_cluster:
  - plugin: redis
    config:
      - servers = ["tcp://127.0.0.1:6380"]

# apache
telegraf_plugins_apache:
  - plugin: apache
    config:
      - urls = ["http://localhost:10180/server-status?auto"]

# nginx
telegraf_plugins_nginx:
  - plugin: nginx
    config:
      - urls = ["http://localhost:8000/server-status"]

# elasticsearch
telegraf_plugins_elasticsearch:
  - plugin: elasticsearch
    config:
      - servers = ["http://localhost:9200"]

# MySql & MariaDB
telegraf_plugins_mysql:
  - plugin: mysql
    config:
      - servers = ["ebs:dlqpdptmdnsdud@tcp(127.0.0.1:13306)/?tls=false"]
      - metric_version = 2
      - table_schema_databases = []
#      - gather_table_schema = true
      - gather_process_list = true
      - gather_user_statistics = true
      - gather_info_schema_auto_inc = true
      - gather_innodb_metrics = true
      - gather_slave_status = true
#      - gather_binary_logs = true
#      - gather_global_variables = true
      - gather_table_io_waits = true
      - gather_table_lock_waits = true
      - gather_index_io_waits = true
      - gather_event_waits = true
      - gather_file_events_stats = true
      - gather_perf_events_statements = true
      - gather_perf_sum_per_acc_per_event = true
      - interval_slow = "10s"
      - perf_summary_events = []
      - perf_events_statements_digest_text_limit = 120
      - perf_events_statements_limit = 250
      - perf_events_statements_time_limit = 86400

# extra configuration - /etc/telegraf/telegraf.d/*
telegraf_plugins_extra: {}
telegraf_plugins_extra_exclusive: False

# RedHat specific settings for convenience
telegraf_redhat_releasever: "$releasever"

telegraf_yum_baseurl:
  amazon: "https://repos.influxdata.com/centos/6/$basearch/stable"
  centos: "https://repos.influxdata.com/rhel/{{ telegraf_redhat_releasever }}/$basearch/stable"
  default: "https://repos.influxdata.com/{{ ansible_distribution|lower }}/{{ telegraf_redhat_releasever }}/$basearch/stable"
  redhat: "https://repos.influxdata.com/rhel/{{ telegraf_redhat_releasever }}/$basearch/stable"
telegraf_yum_gpgkey: "https://repos.influxdata.com/influxdb.key"

telegraf_win_install_dir: 'C:\Telegraf'
telegraf_win_logfile: 'C:\\Telegraf\\telegraf.log'
telegraf_win_include: 'C:\Telegraf\telegraf_agent.d'
telegraf_win_service_args:
  - -service install
  - -config {{ telegraf_win_install_dir }}\telegraf\telegraf.conf
  - --config-directory {{ telegraf_win_include }}

telegraf_mac_user: user
telegraf_mac_group: admin
