- hosts: "{{ targetServers }}"
  vars:
    targetServerName: "httpd"
    playbookHome: "/data/utils/ansible/playbook"

  vars_files:
     - "{{ playbookHome }}/common/common.yml"
     - "{{ playbookHome }}/{{ targetServerName }}/vars/config.yml"

  tasks:
    - name: Create Web(Apache Httpd) Config/Shell Folder
      delegate_to: localhost
      file:
        path: "{{ configRepoHome }}/{{ item }}"
        state: directory
        mode: 0755
        recurse: yes
      with_items: 
        - "web"

    - include: "{{ tasksHome }}/fetchConfig.yml" 
    - include: "{{ tasksHome }}/fetchShell.yml"
