---
  - name: Define User and password
    set_fact: 
      cyrus_sasl_user: "{{ cyrus_sasl_user|default([]) + [ { item.username: { 'password': item.password, 'state': 'present', 'appname': appname, 'domain': domain } } ] }}"
    with_items: "{{ user_info }}"

  - name: Define Sasl Auth Config
    set_fact: 
      cyrus_sasl_config:
        '{{ appname }}':
          pwcheck_method: saslauthd
        argus:
          pwcheck_method: auxprop
          auxprop_plugin: sasldb
          mech_list: DIGEST-MD5
      cyrus_sasl_sasldb_group: "{% if ansible_os_family == 'Debian' %}nogroup{% else %}nobody{% endif %}"
      cyrus_sasl_sasldb_file_permission: "0640"
      cyrus_sasl_package:
       - cyrus-sasl
       - cyrus-sasl-devel
       - cyrus-sasl-lib
       - cyrus-sasl-md5
       - cyrus-sasl-plain

  - name: Install Cyrus-Sasl Roles
    include_role: 
      name: "{{ rolevar }}"
    loop:
      - "{{ rolesPath }}/reallyenglish.cyrus-sasl"  
    loop_control:
      loop_var: rolevar
