---
- hosts: "{{ targetServers }}"
  vars:
    influx_ip : "172.18.0.8"
    influx_db_name : "telegraf"
    influx_udp_port : "8089"
    influx_http_port : "8086"
    redis_port: "6380"
    redis_cluster_port: "6382"
    httpd_port: "18080"
    nginx_port: "8000"
    elasticsearch_port: "9200"
    mysql_username: "mysql_mon"
    mysql_password: "mysql_password"
    mysql_port: "13306"

    postgresql_username: "postgresql_mon"
    postgresql_password: "postgresql_password"

  roles:
    - /sde/cloud/ansible/roles/dj-wasabi.telegraf
