---
  - name: Define Jenkins Variables
    set_fact:
      jenkins_http_port: 8080
      jenkins_admin_username: "admin"
      jenkins_admin_password: "admin"
      jenkins_home: "/var/lib/jenkins"
      jenkins_jobs_upload: true

  - name: Define Jenkins Plugins Variables
    include_tasks: "{{sdePath}}/jenkins_plugins.yml"

  - name: Open Jenkins Http port
    include_tasks: "{{sdePath}}/open_firewall.yml"
    vars:
      work_name: "Jenkins"
      port_info:
        - { protocol: "tcp", port: "{{ jenkins_http_port }}" }

  - name: Install Jenkins Roles
    include_role:
      name: "{{ rolevar }}"
    loop:
      - "{{ rolesPath }}/geerlingguy.java"
      - "{{ rolesPath }}/geerlingguy.jenkins"
    loop_control:
      loop_var: rolevar

  - name: Create Jenkins Jobs
    include_tasks: "jenkins_jobs.yml"
    when: jenkins_jobs_upload is defined and jenkins_jobs_upload
