---
  - name: Modify kernal parameter in sysctl.conf 
    ansible.posix.sysctl:
      name:  "{{ item.name }}"
      value: "{{ item.value }}"
      state: present
      sysctl_set: yes
      reload: yes
    with_items: "{{ sysctl_conf }}"
    when: sysctl_conf is defined

  - name: Modify pam limits
    community.general.pam_limits:
      domain: root
      limit_type: "{{ item.type }}"
      limit_item: "{{ item.item }}"
      value: "{{ item.value }}"
    with_items: "{{ pam_limits }}"
    when: pam_limits is defined
