---
  - name: Define variables for Redmine
    set_fact:
      redmine_version: 4.2.1
      redmine_http_port: 80
      redmine_username: redmine
      redmine_password: redmine
      redmine_database_name: redmine
      remmine_database_host: localhost
      ruby_version: 2.7.3
      ruby_major_version: 2.7
      rubygems_version: 3.1.4

  - name: Define variables for Redmine
    set_fact:
      src_folder: "/usr/local/src"
      local_bin_path: "/usr/local/bin"
      redmine_home: "/home/{{ redmine_username }}/redmine-{{ redmine_version }}" 
      redmine_nginx_home: "/opt/nginx" 
      redmine_nginx_service_path: "/usr/lib/systemd/system" 
      gem_path: "/usr/local/lib/ruby/gems/{{ ruby_major_version }}.0/gems"

  - name: Define variables for Build Sources
    set_fact:
      build_sources:
        - url: "http://cache.ruby-lang.org/pub/ruby/{{ ruby_major_version }}/ruby-{{ ruby_version }}.tar.gz"
          dest: "{{ src_folder }}"
          chdir: "{{ src_folder }}/ruby-{{ ruby_version }}"
          cmd: "./configure --disable-install-doc; make && make install"
        - url: "https://rubygems.org/rubygems/rubygems-{{ rubygems_version}}.tgz" 
          dest: "{{ src_folder }}" 
          chdir: "{{ src_folder }}/rubygems-{{ rubygems_version}}"
          cmd: "/usr/local/bin/ruby setup.rb"
        - url: "https://www.redmine.org/releases/redmine-{{ redmine_version }}.tar.gz"
          dest: "/home/{{ redmine_username }}"
          owner: "{{ redmine_username }}"
          group: "{{ redmine_username }}"

  - name: Define variables for MariaDB
    set_fact:
      mariadb_root_password: "password"
      mariadb_databases:
        - { name: "{{ redmine_database_name }}", encoding: "utf8", collation: "utf8_general_ci" }
      mariadb_users:
        - { name: "{{ redmine_username }}", password: "{{ redmine_password }}", host: "%", priv: "*.*:ALL" }
      ansible_python_interpreter: "{{ ansible_facts.python.executable }}"

  - name: Open Redmine Http port
    include_tasks: "{{sdePath}}/open_firewall.yml"
    vars:
      work_name: "Redmine"
      port_info:
        - { protocol: "http", port: "service" }
        - { protocol: "https", port: "service" }
        - { protocol: "tcp", port: "{{ redmine_http_port }}" }

  - name: Install package dependencies.
    shell: "yum install -y {{ item }}"
    with_items:
      - "mariadb-server mariadb mariadb-devel MySQL-python"
      - "gcc g++ cpp gcc-c++"
      - "ibxslt-devel libyaml-devel libxml2-devel gdbm-devel libffi-devel zlib-devel"
      - "openssl-devel readline-devel curl-devel pcre-devel memcached-devel valgrind-devel"
      - "ImageMagick ImageMagick-devel"
      - "httpd libcurl-devel httpd-devel apr-devel apr-util-devel"

  - name: Restart service MariaDB, in all cases
    ansible.builtin.service:
      name: mariadb
      state: restarted
      enabled: yes

  - name: Create a new database with name '{{ redmine_database_name }}'
    community.mysql.mysql_db:
      name: "{{ item.name }}"
      encoding: "{{ item.encoding }}"
      collation: "{{ item.collation }}"
    with_items: "{{ mariadb_databases }}"

  - name: Create database user using password with all database privileges
    community.mysql.mysql_user:
      name: "{{ item.name }}"
      password: "{{ item.password }}"
      priv: "{{ item.priv }}"
    with_items: "{{ mariadb_users }}"

  - name: Redmine user
    user:
      name: "{{ redmine_username }}"

  - name: Download Build Source
    ansible.builtin.unarchive:
      src: "{{ item.url }}"
      dest: "{{ item.dest }}"
      remote_src: yes
      owner: "{{ item.owner | default('root') }}"
      group: "{{ item.group | default('root') }}"
    with_items: "{{ build_sources }}"

  - name: Compile and Setup 
    ansible.builtin.shell: 
      cmd: "{{ item.cmd }}"
      chdir: "{{ item.chdir }}"
    become_user: "{{ item.owner | default('root') }}"
    when: item.cmd is defined
    with_items: "{{ build_sources }}"

  - name: Install Ruby Gems
    ansible.builtin.shell: "gem install {{ item }}"
    with_items: 
      - "bundler ruby-shadow" 
      - "rails -V"

  - name: Template a file to Redmine Config
    ansible.builtin.template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: "{{ item.owner | default('root') }}"
      group: "{{ item.owner | default('root') }}"
    with_items: 
      - { src: "{{ sdePath }}/templates/redmine.conf.j2", dest: "{{ redmine_home }}/config/configuration.yml", owner: "{{ redmine_username }}" }
      - { src: "{{ sdePath }}/templates/redmine-database.conf.j2", dest: "{{ redmine_home }}/config/database.yml", owner: "{{ redmine_username }}" }

  - name: Install bundle
    ansible.builtin.shell: "cd {{ redmine_home }}; {{ item }}"
    become: true
    become_user: "{{ redmine_username }}"
    with_items: 
      - "{{ local_bin_path }}/bundle install --without development test --path vendor/bundle"
      - "{{ local_bin_path }}/bundle exec {{ local_bin_path }}/rake generate_secret_token"
      - "RAILS_ENV=production {{ local_bin_path }}/bundle exec {{ local_bin_path }}/rake db:migrate"
      - "{{ local_bin_path }}/bundle exec {{ local_bin_path }}/rake redmine:load_default_data RAILS_ENV=production REDMINE_LANG=ko"

  - name: Install passenger nginx module
    ansible.builtin.shell: |
      gem install passenger
      passenger-install-apache2-module --auto

  - name: Regist Passenger Version
    ansible.builtin.shell: "passenger --version | awk '{ print $3 }'"
    register: reg_passenger_version

  - name: Debug
    debug: 
      msg: "{{ reg_passenger_version }}"

  - name: Debug
    set_fact:
      passenger_version: "{{ reg_passenger_version.stdout }}"

  - name: Change Folder mode for httpd process owner 
    shell: "chmod 755 /home/{{ redmine_username }}"

  - name: Template a file to Httpd
    ansible.builtin.template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: "{{ item.owner | default('root') }}"
      group: "{{ item.owner | default('root') }}"
    with_items: 
      - { src: "{{ sdePath }}/templates/redmine-httpd-vhost.conf.j2", dest: "/etc/httpd/conf.d/vhost.conf", owner: "root" }

  - name: Put SELinux in permissive mode. enforcing mode block httpd-passneger.
    ansible.posix.selinux:
      policy: targeted
      state: permissive

  - name: Restart service Apache Httpd, in all cases
    ansible.builtin.service:
      name: httpd
      state: restarted
      enabled: yes
