yum -y install epel-release
yum -y install java-11-openjdk-devel.x86_64
yum -y install https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
yum -y update
yum install -y postgresql96-server
/usr/pgsql-9.6/bin/postgresql96-setup initdb
systemctl enable postgresql-9.6
systemctl start postgresql-9.6
passwd postgres
su - postgres
createuser sonar
psql
ALTER USER sonar WITH ENCRYPTED password 'sonar';
CREATE DATABASE sonar OWNER sonar;


wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-7.9.zip
unzip sonarqube-7.9.zip -d /opt
groupadd sonar
useradd -g sonar sonar
chown -R sonar:sonar /opt/sonarqube-7.9 /opt/sonarqube-7.9/*

sed -i "s/#sonar.jdbc.username=/sonar.jdbc.username=sonar/" /opt/sonarqube-7.9/conf/sonar.properties
sed -i "s/#sonar.jdbc.password=/sonar.jdbc.password=sonar/" /opt/sonarqube-7.9/conf/sonar.properties
sed -i "s/#sonar.jdbc.url=jdbc:postgresql:\/\/localhost\/sonarqube?currentSchema=my_schema/sonar.jdbc.url=jdbc:postgresql:\/\/localhost\/sonar/" /opt/sonarqube-7.9/conf/sonar.properties
sed -i "s/#RUN_AS_USER=/RUN_AS_USER=sonar" /opt/sonarqube-7.9/bin/linux-x86-64/sonar.sh

cat << EOF > /etc/systemd/system/sonar.service
[Unit]
Description=SonarQube service
After=syslog.target network.target

[Service]
Type=simple
User=sonar
Group=sonar
PermissionsStartOnly=true
ExecStart=/bin/nohup java -Xms32m -Xmx32m -Djava.net.preferIPv4Stack=true -jar /opt/sonarqube-7.9/lib/sonar-application-7.9.jar
StandardOutput=syslog
LimitNOFILE=65536
LimitNPROC=8192
TimeoutStartSec=5
Restart=always

[Install]
WantedBy=multi-user.target
EOF

systemctl enable sonar
systemctl start sonar